### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by alirz-pixel** [Advanced-BOJ/Advanced-BOJ-extension#1]
@HeejinYang, @LikeDeer 
괄호 안의 숫자는 우선순위이며, 10에 가까울수록 우선순위가 높습니다.
[2023-03-26 기준] 우선순위는 프로젝트에 필요한 내용일수록 높게 책정하였습니다.

(아이디어 제시는 이슈로 부탁드립니다)

### TODO
- [x] ~~(2) 백준 사이트 내의 광고 제거 (문제 있을 것으로 판단하여 취소)~~
- [x] (6) auto commit 메시지 커스텀 가능하게 하기
- [ ] (8) path 커스텀 기능 추가
- [x] (2) UI 개선
- [ ] (4) 다른 알고리즘 사이트의 auto commiter 지원하기
- [ ] (4) 백준 채점 현황 커스텀에 방금 채점 완료된 채점도 바뀌도록 수정
- [ ] (3) CI/CD 구축
- [ ] (5) 공지사항 replace -> replaceAll...
